#Database
spring.datasource.url=jdbc:mariadb://localhost:3308/stockmvc?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Bi3rs077ZBGSv4lM98w8
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#Jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

